// SPDX-License-Identifier: AGPL-3.0-only

import {
  EDegree,
  EFuncType,
  SecType,
  TrackStyle,
  closeTrack,
  createEmptyFunc,
  type AnchorSection,
  type CurvedSection,
  type Project,
  type StraightSection,
  type Track,
} from '@roller-coaster-designer/core';

/**
 * Handcrafted demo track: anchor at 20 m with a ~20° nose-down, a short
 * drop, a horizontal 90° banking turn, a small climb, then a closure Bezier
 * generated by closeTrack. The roll funcs use Cubic subfuncs so loading
 * the demo exercises the M3 SubFunc evaluator's new branches.
 */
export function createDemoProject(): Project {
  const dropRoll = createEmptyFunc(EFuncType.Roll, 'Drop roll');
  dropRoll.subfuncs.push({
    degree: EDegree.Cubic,
    length: 15,
    startValue: 0,
    endValue: 0,
    arg1: 0,
    centerArg: 0,
    tensionArg: 0,
  });

  // Roll function for the Curved section: domain is the section's
  // ridden angle (degrees), 0..90 in this case. Per-tick value-units
  // are degrees-per-F_HZ-ticks-of-angle (FVD++ semantics).
  const turnRoll = createEmptyFunc(EFuncType.Roll, 'Turn roll');
  turnRoll.subfuncs.push({
    degree: EDegree.Cubic,
    length: 90,
    startValue: 0,
    endValue: 0,
    arg1: 0,
    centerArg: 0,
    tensionArg: 0,
  });

  const climbRoll = createEmptyFunc(EFuncType.Roll, 'Climb roll');
  climbRoll.subfuncs.push({
    degree: EDegree.Cubic,
    length: 10,
    startValue: 0.35,
    endValue: 0,
    arg1: 0,
    centerArg: 0,
    tensionArg: 0,
  });

  const anchor: AnchorSection = {
    type: SecType.Anchor,
    name: 'Start',
    position: [0, 20, 0],
    pitch: -0.35,
    yaw: 0,
    roll: 0,
    speed: 15,
  };
  const drop: StraightSection = {
    type: SecType.Straight,
    name: 'Drop',
    length: 15,
    rollFunc: dropRoll,
  };
  const turn: CurvedSection = {
    type: SecType.Curved,
    name: 'Turn',
    fAngle: 90,
    fRadius: 16,
    fDirection: 90,
    fLeadIn: 15,
    fLeadOut: 15,
    rollFunc: turnRoll,
  };
  const climb: StraightSection = {
    type: SecType.Straight,
    name: 'Climb',
    length: 10,
    rollFunc: climbRoll,
  };

  const openTrack: Track = {
    name: 'Demo',
    style: TrackStyle.Generic,
    heart: 1.1,
    friction: 0,
    resistance: 0,
    smoothers: [],
    sections: [anchor, drop, turn, climb],
  };

  const closed = closeTrack(openTrack);
  return { texturePath: '', tracks: [closed] };
}
