// SPDX-License-Identifier: AGPL-3.0-only
//
// Smoke + parity tests on the 8 Geometric-section corpus FVDs generated by
// `scripts/build-geometric-corpus.ts`. Each file gets four smoke checks
// (byte-stable round-trip, Geometric-only, integrator runs on every
// TIME-mode section, NL2 exporter emits well-formed XML). When a
// .nl2elem golden produced by FVD++ 0.79 sits next to the .fvd, an
// additional parity test diffs every emitted float against gold.

import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

import { readFvd, writeFvd } from './fvd-file.js';
import { exportNL2 } from './nl2-export.js';
import { SecType, DISTANCE } from './section.js';

const here = dirname(fileURLToPath(import.meta.url));
const corpusDir = resolve(here, '../../test/golden/data/fvd-corpus');

const files = readdirSync(corpusDir)
  .filter((f) => f.endsWith('.fvd'))
  .sort();

// Extract every numeric value from emitted vertex / roll tags in the
// NL2 element XML. Order is preserved so two NL2 files with the same
// structure produce comparable float lists.
function extractFloats(xml: string): number[] {
  const out: number[] = [];
  const re = /<(?:x|y|z|ux|uy|uz|rx|ry|rz|coord)>([^<]+)<\/(?:x|y|z|ux|uy|uz|rx|ry|rz|coord)>/g;
  for (const m of xml.matchAll(re)) out.push(Number.parseFloat(m[1]!));
  return out;
}

describe('geometric corpus', () => {
  for (const file of files) {
    describe(file, () => {
      const buf = new Uint8Array(readFileSync(resolve(corpusDir, file)));
      const goldenPath = resolve(corpusDir, file.replace(/\.fvd$/, '.nl2elem'));
      const hasGolden = existsSync(goldenPath);

      it('parses + writes a byte-stable second pass', () => {
        const file1 = readFvd(buf);
        const pass1 = writeFvd(file1);
        const file2 = readFvd(pass1);
        const pass2 = writeFvd(file2);
        expect(pass2.length).toBe(pass1.length);
        for (let i = 0; i < pass1.length; i++) {
          if (pass1[i] !== pass2[i]) {
            throw new Error(`byte mismatch at ${i}: ${pass1[i]} vs ${pass2[i]}`);
          }
        }
      });

      it('contains only Geometric sections', () => {
        const t = readFvd(buf).tracks[0]!;
        expect(t.lSections.length).toBeGreaterThan(0);
        for (const s of t.lSections) {
          expect(s.type).toBe(SecType.Geometric);
        }
      });

      it('integrates every TIME-mode section without throwing', () => {
        const t = readFvd(buf).tracks[0]!;
        for (const s of t.lSections) {
          if (s.bArgument === DISTANCE) continue;
          expect(s.lNodes.length).toBeGreaterThan(1);
        }
      });

      it('exports well-formed NL2 XML over the TIME-mode prefix', () => {
        const t = readFvd(buf).tracks[0]!;
        let toIndex = -1;
        for (let i = 0; i < t.lSections.length; i++) {
          if (t.lSections[i]!.bArgument === DISTANCE) break;
          toIndex = i;
        }
        if (toIndex < 0) return;
        const xml = exportNL2(t, 2.0, 0, toIndex);
        expect(xml).toMatch(/^<\?xml/);
        expect(xml).toContain('<vertex>');
        expect(xml).toContain('<roll>');
        expect(xml).toContain('</root>');
      });

      if (hasGolden) {
        it('matches FVD++ gold .nl2elem (count + numerical parity)', () => {
          const t = readFvd(buf).tracks[0]!;
          const ours = exportNL2(t, 2.0, 0, t.lSections.length - 1);
          const gold = readFileSync(goldenPath, 'utf8');
          const ourF = extractFloats(ours);
          const goldF = extractFloats(gold);

          // Length mismatches mean our exporter chose different
          // sampling indices than FVD — caller logs and skips the
          // numerical diff. List of files where this is currently
          // expected; populate as the integrators sharpen.
          const knownLengthMismatch = new Set<string>([]);
          if (ourF.length !== goldF.length) {
            if (knownLengthMismatch.has(file)) {
              // eslint-disable-next-line no-console
              console.log(
                `${file}: known-pending length mismatch — ours=${ourF.length} gold=${goldF.length}`,
              );
              return;
            }
            throw new Error(
              `${file}: float count mismatch — ours=${ourF.length} gold=${goldF.length}`,
            );
          }

          let maxAbs = 0;
          let maxIdx = -1;
          for (let i = 0; i < ourF.length; i++) {
            const d = Math.abs(ourF[i]! - goldF[i]!);
            if (d > maxAbs) {
              maxAbs = d;
              maxIdx = i;
            }
          }
          // eslint-disable-next-line no-console
          console.log(
            `${file}: maxAbs=${maxAbs.toFixed(5)} @${maxIdx} gold=${goldF[maxIdx]} ours=${ourF[maxIdx]}`,
          );
          // 1.2 m budget while parity tightens — multisub passes at
          // <5 mm, kinematics at 3 cm; pitch/yaw drift a little under
          // 1 m by the end of a 135-m track. Tighten as float32
          // emulation extends across the Geometric integrator.
          expect(maxAbs).toBeLessThan(1.2);
        });
      }
    });
  }
});
