// SPDX-License-Identifier: AGPL-3.0-only
//
// Smoke tests on geo-corpus.fvd — the Geometric-section parameter sweep
// generated by `scripts/build-geometric-corpus.ts`. Until FVD++ emits a
// matching geo-corpus.nl2elem golden, these confirm:
//   1. The .fvd round-trips through our reader/writer byte-stable.
//   2. The integrator runs without exceptions for every TIME-mode
//      section (DISTANCE-mode integrator is not yet ported, so those
//      sections are loaded + saved only; gold from FVD will drive that
//      work once it lands).
//   3. The NL2 exporter produces well-formed XML.

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

import { readFvd, writeFvd } from './fvd-file.js';
import { exportNL2 } from './nl2-export.js';
import { SecType, DISTANCE } from './section.js';

const here = dirname(fileURLToPath(import.meta.url));
const corpusPath = resolve(here, '../../test/golden/data/fvd-corpus/geo-corpus.fvd');

describe('geo-corpus.fvd', () => {
  if (!existsSync(corpusPath)) {
    it.skip('corpus file missing — run scripts/build-geometric-corpus.ts', () => undefined);
    return;
  }
  const buf = new Uint8Array(readFileSync(corpusPath));

  it('parses + writes a byte-stable second pass', () => {
    const file1 = readFvd(buf);
    const pass1 = writeFvd(file1);
    const file2 = readFvd(pass1);
    const pass2 = writeFvd(file2);
    expect(pass2.length).toBe(pass1.length);
    for (let i = 0; i < pass1.length; i++) {
      if (pass1[i] !== pass2[i]) {
        throw new Error(`byte mismatch at ${i}: ${pass1[i]} vs ${pass2[i]}`);
      }
    }
  });

  it('contains only Geometric sections', () => {
    const t = readFvd(buf).tracks[0]!;
    expect(t.lSections.length).toBeGreaterThan(0);
    for (const s of t.lSections) {
      expect(s.type).toBe(SecType.Geometric);
    }
  });

  it('integrates every TIME-mode section without throwing', () => {
    const t = readFvd(buf).tracks[0]!;
    for (const s of t.lSections) {
      if (s.bArgument === DISTANCE) continue;
      expect(s.lNodes.length).toBeGreaterThan(1);
    }
  });

  it('exports well-formed NL2 XML over the TIME-mode prefix', () => {
    const t = readFvd(buf).tracks[0]!;
    let toIndex = -1;
    for (let i = 0; i < t.lSections.length; i++) {
      if (t.lSections[i]!.bArgument === DISTANCE) break;
      toIndex = i;
    }
    expect(toIndex).toBeGreaterThanOrEqual(0);
    const xml = exportNL2(t, 2.0, 0, toIndex);
    expect(xml).toMatch(/^<\?xml/);
    expect(xml).toContain('<vertex>');
    expect(xml).toContain('<roll>');
    expect(xml).toContain('</root>');
  });
});
